import { createContext, useContext, useState } from 'react'

const translations = {
  tr: {
    // Navigation
    'nav.overview': 'Genel Bakış',
    'nav.assets': 'Portföy',
    'nav.market': 'Piyasa',
    'market.title': 'Piyasa',
    'market.gainers': 'En Çok Yükselen',
    'market.losers': 'En Çok Düşen',
    'market.change': 'Değişim',
    'nav.transactions': 'İşlemler',
    'nav.analytics': 'Analiz',
    'nav.logout': 'Çıkış Yap',

    // Overview
    'overview.title': 'Genel Bakış',
    'overview.netWorth': 'Net Varlık',
    'overview.cash': 'Nakit',
    'overview.investments': 'Yatırımlar',
    'overview.quickAdd': 'Hızlı Ekle',
    'overview.allocation': 'Dağılım',
    'overview.allAssets': 'Tüm Varlıklar',
    'overview.assetCount': 'varlık',

    // Transactions
    'transactions.title': 'Tüm İşlemler',
    'transactions.search': 'Ara...',
    'transactions.filter': 'Filtrele',
    'transactions.noResults': 'İşlem bulunamadı',
    'transactions.assetBuy': 'Alış',
    'transactions.assetSell': 'Satış',

    // Assets
    'assets.title': 'Portföy',
    'assets.gold': 'Altın',
    'assets.goldSoon': 'Altın yakında eklenecek.',
    'assets.goldGram': 'Altın (gram)',
    'assets.grams': 'Gram',
    'assets.pricePerGram': 'Gram Fiyatı',
    'assets.grandTotal': 'Toplam Portföy',
    'assets.amount': 'Miktar',
    'assets.buyRate': 'Alış Kuru',
    'assets.currentRate': 'Güncel Kur',
    'assets.addAsset': 'Varlık Ekle',
    'assets.currency': 'Döviz',
    'assets.stock': 'Hisse',
    'assets.name': 'Varlık',
    'assets.symbol': 'Sembol',
    'assets.quantity': 'Adet',
    'assets.price': 'Fiyat',
    'assets.value': 'Değer',
    'assets.purchasePrice': 'Alış Fiyatı',
    'assets.currentPrice': 'Güncel Fiyat',
    'assets.cost': 'Maliyet',
    'assets.currentValue': 'Güncel Değer',
    'assets.profitLoss': 'Kâr/Zarar',
    'assets.edit': 'Düzenle',
    'assets.noAssets': 'Henüz varlık eklenmedi.',
    'assets.buy': 'Al',
    'assets.sell': 'Sat',
    'assets.buyAsset': 'Varlık Al',
    'assets.searchPlaceholder': 'Hisse ara (ör. Türk Hava Yolları, THYAO)',
    'drawer.marketStats': 'Piyasa İstatistikleri',
    'drawer.previousClose': 'Önceki Kapanış',
    'drawer.dayRange': 'Gün Aralığı',
    'drawer.week52Range': '52 Hafta Aralığı',
    'drawer.volume': 'Hacim',
    'drawer.yourPosition': 'Pozisyonun',
    'drawer.chart': 'Grafik',
    'drawer.lotHistory': 'Alım-Satım Geçmişi',
    'drawer.date': 'Tarih',
    'drawer.noHistory': 'Kayıt yok',
    'drawer.expand': 'Genişlet',
    'drawer.collapse': 'Küçült',
    'assets.sellAsset': 'Varlık Sat',
    'assets.unitPrice': 'Alış Fiyatı',
    'assets.currencyLabel': 'Para Birimi',
    'assets.purchaseDate': 'Alım Tarihi',
    'assets.avgCost': 'Ort. Maliyet',
    'assets.priceUnavailable': 'Fiyat alınamadı',
    'assets.realizedPL': 'Gerçekleşen K/Z',
    'assets.confirmDelete': 'Bu varlığı silmek istediğine emin misin?',

    // Common
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.add': 'Ekle',
    'common.amount': 'Tutar',
    'common.category': 'Kategori',
    'common.date': 'Tarih',
    'common.description': 'Açıklama',
    'common.tags': 'Etiketler',
    'common.type': 'Tür',
    'common.total': 'Toplam',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.selectDate': 'Tarih seçin',
    'common.today': 'Bugün',
    'common.clear': 'Temizle',
    'common.optional': 'opsiyonel',

    // Analytics
    'analytics.allocation': 'Varlık Dağılımı',

    // Auth
    'auth.appName': 'Investment Tracker',
    'auth.welcomeBack': 'Tekrar Hoş Geldiniz',
    'auth.signInSubtitle': 'Hesabınıza giriş yapın',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.signingIn': 'Giriş yapılıyor...',
    'auth.signIn': 'Giriş Yap',
    'auth.noAccount': 'Hesabınız yok mu?',
    'auth.createOne': 'Hesap oluşturun',
    'auth.loginTagline1': 'Portföylerini takip et.',
    'auth.loginTagline2': 'Piyasaları izle.',
    'auth.loginTagline3': 'Bir adım önde ol.',
    'auth.loginSubtagline': 'Gerçek zamanlı veri. Temiz içgörüler. Tam kontrol.',
    'auth.createAccount': 'Hesap Oluştur',
    'auth.createAccountSubtitle': 'Ücretsiz hesabınızı oluşturun',
    'auth.creatingAccount': 'Hesap oluşturuluyor...',
    'auth.alreadyHaveAccount': 'Zaten hesabınız var mı?',
    'auth.registerTagline1': 'Bugün takibe başla.',
    'auth.registerTagline2': 'Portföyünü oluştur.',
    'auth.registerTagline3': 'Finansını yönet.',
    'auth.registerSubtagline': 'Saniyeler içinde hesap oluşturun. Kredi kartı gerekmez.',
    'auth.redirecting': 'Yönlendiriliyor...',
    'auth.copyright': '© 2025 Investment Tracker',
    'auth.errEmailRequired': 'E-posta gerekli',
    'auth.errEmailInvalid': 'Geçerli bir e-posta girin',
    'auth.errPasswordRequired': 'Parola gerekli',
    'auth.errPasswordShort': 'Parola en az 8 karakter olmalı',
    'auth.errInvalidCredentials': 'E-posta veya parola hatalı',
    'auth.errEmailExists': 'Bu e-posta zaten kayıtlı',
    'auth.errGeneric': 'İşlem başarısız, bilgileri kontrol edin',
    'auth.showPassword': 'Şifreyi göster',
    'auth.hidePassword': 'Şifreyi gizle',

    // Filters
    'filter.all': 'Tümü',
    'filter.thisMonth': 'Bu Ay',
    'filter.thisYear': 'Bu Yıl',
    'filter.dateRange': 'Tarih Aralığı',
    'filter.from': 'Başlangıç',
    'filter.to': 'Bitiş',
  },
  en: {
    'nav.overview': 'Overview',
    'nav.assets': 'Portfolio',
    'nav.market': 'Market',
    'market.title': 'Market',
    'market.gainers': 'Top Gainers',
    'market.losers': 'Top Losers',
    'market.change': 'Change',
    'nav.transactions': 'Transactions',
    'nav.analytics': 'Analytics',
    'nav.logout': 'Logout',
    'overview.title': 'Overview',
    'overview.netWorth': 'Net Worth',
    'overview.cash': 'Cash',
    'overview.investments': 'Investments',
    'overview.allocation': 'Allocation',
    'overview.allAssets': 'All Assets',
    'overview.assetCount': 'assets',
    'overview.quickAdd': 'Quick Add',
    'transactions.title': 'All Transactions',
    'transactions.search': 'Search...',
    'transactions.filter': 'Filter',
    'transactions.noResults': 'No transactions found',
    'transactions.assetBuy': 'Buy',
    'transactions.assetSell': 'Sell',
    'assets.title': 'Portfolio',
    'assets.gold': 'Gold',
    'assets.goldSoon': 'Gold coming soon.',
    'assets.goldGram': 'Gold (gram)',
    'assets.grams': 'Grams',
    'assets.pricePerGram': 'Price / gram',
    'assets.grandTotal': 'Total Portfolio',
    'assets.amount': 'Amount',
    'assets.buyRate': 'Buy Rate',
    'assets.currentRate': 'Current Rate',
    'assets.addAsset': 'Add Asset',
    'assets.currency': 'Currency',
    'assets.stock': 'Stock',
    'assets.name': 'Asset',
    'assets.symbol': 'Symbol',
    'assets.quantity': 'Quantity',
    'assets.price': 'Price',
    'assets.value': 'Value',
    'assets.purchasePrice': 'Purchase Price',
    'assets.currentPrice': 'Current Price',
    'assets.cost': 'Cost',
    'assets.currentValue': 'Current Value',
    'assets.profitLoss': 'Profit/Loss',
    'assets.edit': 'Edit',
    'assets.noAssets': 'No assets added yet.',
    'assets.buy': 'Buy',
    'assets.sell': 'Sell',
    'assets.buyAsset': 'Buy Asset',
    'assets.searchPlaceholder': 'Search stock (e.g. Turkish Airlines, THYAO)',
    'drawer.marketStats': 'Market Stats',
    'drawer.previousClose': 'Previous Close',
    'drawer.dayRange': 'Day Range',
    'drawer.week52Range': '52 Week Range',
    'drawer.volume': 'Volume',
    'drawer.yourPosition': 'Your Position',
    'drawer.chart': 'Chart',
    'drawer.lotHistory': 'Transaction History',
    'drawer.date': 'Date',
    'drawer.noHistory': 'No records',
    'drawer.expand': 'Expand',
    'drawer.collapse': 'Collapse',
    'assets.sellAsset': 'Sell Asset',
    'assets.unitPrice': 'Purchase Price',
    'assets.currencyLabel': 'Currency',
    'assets.purchaseDate': 'Purchase Date',
    'assets.avgCost': 'Avg. Cost',
    'assets.priceUnavailable': 'Price unavailable',
    'assets.realizedPL': 'Realized P/L',
    'assets.confirmDelete': 'Are you sure you want to delete this asset?',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.amount': 'Amount',
    'common.category': 'Category',
    'common.date': 'Date',
    'common.description': 'Description',
    'common.tags': 'Tags',
    'common.type': 'Type',
    'common.total': 'Total',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.selectDate': 'Pick a date',
    'common.today': 'Today',
    'common.clear': 'Clear',
    'common.optional': 'optional',
    'analytics.allocation': 'Asset Allocation',
    'auth.appName': 'Investment Tracker',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInSubtitle': 'Sign in to your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signingIn': 'Signing in...',
    'auth.signIn': 'Sign in',
    'auth.noAccount': "Don't have an account?",
    'auth.createOne': 'Create one',
    'auth.loginTagline1': 'Track your portfolios.',
    'auth.loginTagline2': 'Monitor your markets.',
    'auth.loginTagline3': 'Stay ahead.',
    'auth.loginSubtagline': 'Real-time data. Clean insights. Full control.',
    'auth.createAccount': 'Create account',
    'auth.createAccountSubtitle': 'Get started with your free account',
    'auth.creatingAccount': 'Creating account...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.registerTagline1': 'Start tracking today.',
    'auth.registerTagline2': 'Build your portfolio.',
    'auth.registerTagline3': 'Own your finances.',
    'auth.registerSubtagline': 'Create an account in seconds. No credit card required.',
    'auth.redirecting': 'Redirecting...',
    'auth.copyright': '© 2025 Investment Tracker',
    'auth.errEmailRequired': 'Email is required',
    'auth.errEmailInvalid': 'Enter a valid email',
    'auth.errPasswordRequired': 'Password is required',
    'auth.errPasswordShort': 'Password must be at least 8 characters',
    'auth.errInvalidCredentials': 'Invalid email or password',
    'auth.errEmailExists': 'This email is already registered',
    'auth.errGeneric': 'Something went wrong, check your details',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'filter.all': 'All',
    'filter.thisMonth': 'This Month',
    'filter.thisYear': 'This Year',
    'filter.dateRange': 'Date Range',
    'filter.from': 'From',
    'filter.to': 'To',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'tr')

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key

  const switchLang = (newLang) => {
    setLang(newLang)
    localStorage.setItem('lang', newLang)
  }

  return (
    <LanguageContext.Provider value={{ lang, t, switchLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
