name: WSL Dev Deploy

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy secrets
        run: |
          cp ~/secrets/.env $GITHUB_WORKSPACE/.env
          cp ~/secrets/portfolio-appsettings.Development.json $GITHUB_WORKSPACE/portfolio-service/appsettings.Development.json
          cp ~/secrets/market-appsettings.Development.json $GITHUB_WORKSPACE/market-service/appsettings.Development.json

      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE
          docker compose down
          docker compose up --build -d
