name: WSL Dev Deploy

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy .env
        run: |
          cp ~/investment-tracker/.env $GITHUB_WORKSPACE/.env

      - name: Copy appsettings.Development.json files
        run: |
          cp ~/investment-tracker/portfolio-service/appsettings.Development.json $GITHUB_WORKSPACE/portfolio-service/appsettings.Development.json
          cp ~/investment-tracker/market-service/appsettings.Development.json $GITHUB_WORKSPACE/market-service/appsettings.Development.json

      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE
          docker compose down
          docker compose up --build -d
